// Generated by https://quicktype.io
export interface UsersResponse {
    page:        number;
    per_page:    number;
    total:       number;
    total_pages: number;
    data:        User[];
    support:     Support;
  }
  
  // Generated by https://quicktype.io
  export interface UserResponse {
    data:    User;
    support: Support;
  }
  
  export interface User {
    id:         number | null;
    email:      string;
    first_name: string;
    last_name:  string;
    avatar:     string;
  }

  export const NULL_USER: User = {
    id: null,
    email: '',
    first_name: '',
    last_name: '',
    avatar: ''
  };
  
  export interface Support {
    url:  string;
    text: string;
  }